### ISSUE TITLE
An error occurred while acess stackoverflow.com

### ISSUE THREAD

**Issue by ezefranca** [GuillaumeFalourd/stackoverflow-login-fanatic-badge#1]
**An error occurred while acess stackoverflow.com**

<img width="971" alt="Screen Shot 2021-04-08 at 11 17 25" src="https://user-images.githubusercontent.com/3648336/114043049-54ad7880-985c-11eb-950d-f24fe2114754.png">

Mesmo com as secrets configuradas:

<img width="954" alt="Screen Shot 2021-04-08 at 11 20 30" src="https://user-images.githubusercontent.com/3648336/114043179-70188380-985c-11eb-86f1-2ba572015cd0.png">

**Comment by GuillaumeFalourd** [comment]
Thanks for the feedback @ezefranca 👍🏼 

Sometimes, a `Captcha` window appears on StackOverflow.

In that case, the workflow fails and you'll be informed if Github Actions notifications are configured.

If you want to check it locally, you can use the [ritchie formula](https://github.com/GuillaumeFalourd/formulas-python/tree/master/stackoverflow/login) on your terminal, commenting [those lines](https://github.com/GuillaumeFalourd/formulas-python/blob/15f1f56630131a2d3202ca7a1f685c2708a4815b/stackoverflow/login/src/formula/formula.py#L15-L18) on the formula to see the workflow on Chrome.

**Comment by GuillaumeFalourd** [comment]
I updated the main README file to make it clearer that getting an error when the `captcha` window appears is an expected behaviour.

**Comment by GuillaumeFalourd** [comment]
I'll close the ISSUE @ezefranca as I added the description to README file 👍🏼 

If you have any other question, feel free to open another ISSUE or contact me through DM on social medias 😄
